//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLang.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement of Rent.
        /// </summary>
        public static string Agreement_of_Rent {
            get {
                return ResourceManager.GetString("Agreement of Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement to Sale.
        /// </summary>
        public static string Agreement_to_Sale {
            get {
                return ResourceManager.GetString("Agreement to Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Conversion Tax.
        /// </summary>
        public static string Amount_of_Conversion_Tax {
            get {
                return ResourceManager.GetString("Amount of Conversion Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Proccessing fees.
        /// </summary>
        public static string Amount_of_Proccessing_fees {
            get {
                return ResourceManager.GetString("Amount of Proccessing fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application No.
        /// </summary>
        public static string Application_No {
            get {
                return ResourceManager.GetString("Application No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Uncultivated Land.
        /// </summary>
        public static string Area_of_Uncultivated_Land {
            get {
                return ResourceManager.GetString("Area of Uncultivated Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower&apos;s Email.
        /// </summary>
        public static string Borrower_s_Email {
            get {
                return ResourceManager.GetString("Borrower\'s Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower&apos;s Name.
        /// </summary>
        public static string Borrower_s_Name {
            get {
                return ResourceManager.GetString("Borrower\'s Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Officer.
        /// </summary>
        public static string Circle_Officer {
            get {
                return ResourceManager.GetString("Circle Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Survey.
        /// </summary>
        public static string City_Survey {
            get {
                return ResourceManager.GetString("City Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Talati.
        /// </summary>
        public static string City_Talati {
            get {
                return ResourceManager.GetString("City Talati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent document.
        /// </summary>
        public static string Consent_document {
            get {
                return ResourceManager.GetString("Consent document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Tax.
        /// </summary>
        public static string Conversion_Tax {
            get {
                return ResourceManager.GetString("Conversion Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of letter for payment of Conversion Tax.
        /// </summary>
        public static string Date_of_letter_for_payment_of_Conversion_Tax {
            get {
                return ResourceManager.GetString("Date of letter for payment of Conversion Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        public static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of Conversion Tax Amount received.
        /// </summary>
        public static string Details_of_Conversion_Tax_Amount_received {
            get {
                return ResourceManager.GetString("Details of Conversion Tax Amount received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Details.
        /// </summary>
        public static string Document_Details {
            get {
                return ResourceManager.GetString("Document Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        public static string Document_No_ {
            get {
                return ResourceManager.GetString("Document No.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Payment.
        /// </summary>
        public static string Document_Payment {
            get {
                return ResourceManager.GetString("Document Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Document_Type {
            get {
                return ResourceManager.GetString("Document Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Dhara Center.
        /// </summary>
        public static string e_Dhara_Center {
            get {
                return ResourceManager.GetString("e-Dhara Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Details in Revenue Record.
        /// </summary>
        public static string Entry_Details_in_Revenue_Record {
            get {
                return ResourceManager.GetString("Entry Details in Revenue Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        public static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram Panchayat.
        /// </summary>
        public static string Gram_Panchayat {
            get {
                return ResourceManager.GetString("Gram Panchayat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Instred into the Application.
        /// </summary>
        public static string Mail_Instred_into_the_Application {
            get {
                return ResourceManager.GetString("Mail Instred into the Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mamlatdar.
        /// </summary>
        public static string Mamlatdar {
            get {
                return ResourceManager.GetString("Mamlatdar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured or not.
        /// </summary>
        public static string Measured_or_not {
            get {
                return ResourceManager.GetString("Measured or not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Application.
        /// </summary>
        public static string Measurement_Application {
            get {
                return ResourceManager.GetString("Measurement Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Application Number.
        /// </summary>
        public static string Measurement_Application_Number {
            get {
                return ResourceManager.GetString("Measurement Application Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string Mobile_Number {
            get {
                return ResourceManager.GetString("Mobile Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Instred into the Application.
        /// </summary>
        public static string Mobile_Number_Instred_into_the_Application {
            get {
                return ResourceManager.GetString("Mobile Number Instred into the Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Deed.
        /// </summary>
        public static string Mortgage_Deed {
            get {
                return ResourceManager.GetString("Mortgage Deed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Number.
        /// </summary>
        public static string Note_Number {
            get {
                return ResourceManager.GetString("Note Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion.
        /// </summary>
        public static string Opinion {
            get {
                return ResourceManager.GetString("Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other(if any).
        /// </summary>
        public static string Other_if_any_ {
            get {
                return ResourceManager.GetString("Other(if any)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receipt.
        /// </summary>
        public static string Payment_Receipt {
            get {
                return ResourceManager.GetString("Payment Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Details.
        /// </summary>
        public static string Property_Details {
            get {
                return ResourceManager.GetString("Property Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number for payment of Conversion Tax.
        /// </summary>
        public static string Reference_Number_for_payment_of_Conversion_Tax {
            get {
                return ResourceManager.GetString("Reference Number for payment of Conversion Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number for payment of Measurement Fees.
        /// </summary>
        public static string Reference_Number_for_payment_of_Measurement_Fees {
            get {
                return ResourceManager.GetString("Reference Number for payment of Measurement Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number for payment of Proccessing Fees.
        /// </summary>
        public static string Reference_Number_for_payment_of_Proccessing_Fees {
            get {
                return ResourceManager.GetString("Reference Number for payment of Proccessing Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Deed.
        /// </summary>
        public static string Release_Deed {
            get {
                return ResourceManager.GetString("Release Deed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales document.
        /// </summary>
        public static string Sales_document {
            get {
                return ResourceManager.GetString("Sales document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller&apos;s Name.
        /// </summary>
        public static string Seller_s_Name {
            get {
                return ResourceManager.GetString("Seller\'s Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Number.
        /// </summary>
        public static string Survey_Number {
            get {
                return ResourceManager.GetString("Survey Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taluka.
        /// </summary>
        public static string Taluka {
            get {
                return ResourceManager.GetString("Taluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncultivated Application.
        /// </summary>
        public static string Uncultivated_Application {
            get {
                return ResourceManager.GetString("Uncultivated Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
    }
}
